### ISSUE TITLE
Radio Not Initialized

### ISSUE THREAD

**Issue by Darozas** [rstrouse/ESPSomfy-RTS#232]
Hi All 

Can any one point me to right direction please.

Got all wiring correct checked 10 times but still get this "Radio Not Initialized"

Is there any other ways of checking this?

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/19796221/a2b7330f-d1ba-47ca-a73a-bbd516c5df06)

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/19796221/7ef5be36-7210-4551-9e48-7be9ed65757a)
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/19796221/399550c8-cf93-430c-94e1-482d1ea49055)

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/19796221/4051ff54-fa5b-42e3-988c-3d8389c0ddc3)

Thanks in advance.

Regards

**Comment by Darozas** [comment]
I have iven installed ESPSompfy on known working module as i still got it soldered to board changed pinout to match and no go still. I know this module works in this setup as i been using it on water meter.

**Comment by rstrouse** [comment]
That is not an E07-M1101D you will need to use the the mapping that lines up with the D-SUN.  However, it looks like they also swapped the GDO0 (TX) and GDO2 (RX) pins on that version.  I love the board but if you used the E07-M1101D mapping then it is not correct.  Please note that the DSUN is also not quite right but you can make it work by simply swapping the pins if the board is wired to the E07-M1101D.

If the wiring for the board is set up for the E07-M1101D then your pin settings should be as follows.  Essentially you need to trace the pin function to the setting in the software.  The reason it is giving you a Radio not Initialized is because the SPI pins are not correct.
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/47839015/2c1cbf57-35c7-4aea-be16-7b0b3604d035)

**Comment by Darozas** [comment]
I Have Used this for pinout.

Ill try to change to see if it starts work.

PCB files will be yours once proven to work so than you can upload on your git 

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/19796221/a8ce7131-ef35-415c-bd51-28fe2ecb263c)

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/19796221/8984ede7-d5fc-4d94-88b1-89cf2afc7e1f)

**Comment by rstrouse** [comment]
Yep that is the pinout for the E07-M1101D.  Your transceiver remapped the pins to different pinouts so pin 4 on the E07 is CSN but on your Transceiver it is SCK.  There is a footnote on the table to indicate that but fortunately some remapping on the software should solve the issue.

**Comment by Darozas** [comment]
I still dont get it as pints on ESP corresponds to once on CC1101 

Mosi 23
Miso19
CSK 18
CSN 5 

But not working.

I have puled out ESP that i have used before with module soldered that been working and eve this board giving me headache

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/19796221/d9ef8592-f598-441b-8960-5b6c5582f1b3)

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/19796221/458fe44f-786e-40b7-811d-607dc0105d55)


Regards

**Comment by Darozas** [comment]
> That is not an E07-M1101D you will need to use the the mapping that lines up with the D-SUN. However, it looks like they also swapped the GDO0 (TX) and GDO2 (RX) pins on that version. I love the board but if you used the E07-M1101D mapping then it is not correct. Please note that the DSUN is also not quite right but you can make it work by simply swapping the pins if the board is wired to the E07-M1101D.
> 
> If the wiring for the board is set up for the E07-M1101D then your pin settings should be as follows. Essentially you need to trace the pin function to the setting in the software. The reason it is giving you a Radio not Initialized is because the SPI pins are not correct. ![image](https://private-user-images.githubusercontent.com/47839015/295703768-2c1cbf57-35c7-4aea-be16-7b0b3604d035.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MTkwMTMsIm5iZiI6MTcwNDkxODcxMywicGF0aCI6Ii80NzgzOTAxNS8yOTU3MDM3NjgtMmMxY2JmNTctMzVjNy00YWVhLWJlMTYtN2IwYjM2MDRkMDM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDIwMzE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiMTRlYzNkZGRjZGIzYmFiYjBhZWMxNWIzZjcwMWI4NWU4OTYxNDY2NWQzNTdkZDBlZWQxMGRmNzc1ZGM1MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QPvRMf7bhooz3L0oSnoDwCfvVEgv85RrhX3xZcE_i4A)

I Have Noticed you have "Enable Radio" ticked is that should be ticked?

**Comment by rstrouse** [comment]
Yes it should be ticked or it will not initialize and enable the radio.

**Comment by Darozas** [comment]
Hi Thanks "Message Gone" 

How to test if its working? i been using virtual remote but not getting any logs. Is logs only recorded using Somfy Remote ?

Regards

**Comment by rstrouse** [comment]
That is a receive only log since transmit output doesn't mean anything.  If the radio not initialized message is gone it is communicating over the SPI interface.  Adding this into the logs would just be noise.  If you had two devices you would see the other one receiving.

**Comment by Darozas** [comment]
> Yes it should be ticked or it will not initialize and enable the radio.

Ok Thanks.

Got strange issue One module sends commands another one receives .

But wont work other way ? So the one that receives wont send or the one that sends wont receive ?

Is this normal?

Regards

Receiving end 

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/19796221/fc3dfce9-656c-44d5-b157-1bb23ba4b60b)
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/19796221/67521f38-4491-4d14-9a74-3b09eb63cd19)


Transmitting end 

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/19796221/cd01a91c-565a-44cc-aa1d-f21e21129bd4)

**Comment by rstrouse** [comment]
Double check which pin you have connected to GDO0 and GDO2 for the configuration that you have labeled as the transmitting end.  Change the configuration on that one to GPIO13 for both TX and RX.  In that configuration ESPSomfy RTS will multiplex GDO0 to send and receive on the same pin.

**Comment by Darozas** [comment]
This one sends 

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/19796221/9c6a38f0-6922-4ce4-89b0-fec313974c15)


This one receives 

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/19796221/83f31503-1912-4051-9b1a-694dd4b27d0b)

Keep Plying with TX RX on both but cant send message back to sender 

Regards

**Comment by Darozas** [comment]
Motor magickly started to work but still get no logs on Sender

Sender controlling motor

**Comment by rstrouse** [comment]
The sender will not place a frame in the log.  Only a receiver will.

**Comment by Darozas** [comment]
So why receiver receives but wont send?

I tried TX RX
          RX TX
          TX TX 

But no joy

Regards

**Comment by rstrouse** [comment]
The transceiver can only send on the pin marked GDO0.  You should trace this wire from the GDO0 (pin 3) on the transceiver to the pin on the esp32 that you have the this connected to.  Then ensure the that pin is the pin you have selected in the TX dropdown.

**Comment by Darozas** [comment]
Unit working.

I have purchased Somfly remote and its loging.

Thanks for your superb work.

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/19796221/1430630c-ba7b-440c-ad41-7f632d0ecf50)

Regards
